// <auto-generated />
using Collector.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Collector.Migrations
{
    [DbContext(typeof(CityContext))]
    partial class CityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Collector.Entity.Tables.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityName");

                    b.Property<string>("CityUrl");

                    b.Property<double>("CrimeIndex");

                    b.Property<double>("DivorceRate");

                    b.Property<double>("HappyScore");

                    b.Property<int>("Hopsital");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<long>("MedianIncome");

                    b.Property<int>("NaturalDisasters");

                    b.Property<double>("NeverMarriedRate");

                    b.Property<double>("NowMarriedRate");

                    b.Property<long>("Police");

                    b.Property<long>("Population");

                    b.Property<double>("SadScore");

                    b.Property<double>("SeparetedRate");

                    b.Property<string>("StateName");

                    b.Property<double>("WidowedRate");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Collector.Entity.Tables.TourTrap", b =>
                {
                    b.Property<int>("TourTrapId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CityId");

                    b.Property<string>("Title");

                    b.HasKey("TourTrapId");

                    b.HasIndex("CityId");

                    b.ToTable("TourTraps");
                });

            modelBuilder.Entity("Collector.Entity.Tables.TourTrap", b =>
                {
                    b.HasOne("Collector.Entity.Tables.City", "City")
                        .WithMany("TouristTraps")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
